---
version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  debug_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  main_lib_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    delay: True
    filename: log/main_lib.log

loggers:
  simpleExample:
    level: DEBUG
    handlers: [debug_console]
    propagate: no

  main_lib:
    level: DEBUG
    handlers: [main_lib_file_handler]

  src.hello:
    level: DEBUG
    handlers: [debug_console]
    propagate: no

root:
  level: DEBUG
  handlers: [debug_console]
